name: Build and Release Go Windows Binary

on:
  push:
    tags:
      - 'v*'   # Срабатывает только при пуше тега вида v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'    # Используй нужную версию Go

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -o myapp.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: myapp.exe
